TRAIN:
  ENABLE: False
  DATASET: meccano
  BATCH_SIZE: 12
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True

TEST:
  ENABLE: True
  DATASET: meccano
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: ''
  # NUM_SPATIAL_CROPS: 1
  NUM_SPATIAL_CROPS: 3

# Knowledge Distillation specific configs
DISTILLATION:
  ENABLE: False
  TEMPERATURE: 4.0
  ALPHA: 0.5  # Weight for hard loss vs soft loss
  TEACHER_ARCH: slowfast 
  STUDENT_ARCH: x3d
  TEACHER_CFG_FILE: "/home/milkyway/Desktop/Student Thesis/Slowfast/slowfast/configs/meccano/distilled/SlowFast_8x8_50_teacher.yaml"    # Path to SlowFast config file
  STUDENT_CHECKPOINT: "/home/milkyway/Desktop/Student Thesis/Slowfast/slowfast/intermediate_results/X3D_M_pruned_for_disillation_exp2/pruning_rate_25/pruned_model_taylor_ratio25.pyth"  # Path to initialize student model (optional)

# Student model configs (X3D-M)
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
  BN_LIN5: True
  SCALE_RES2: True

DATA:
  PATH_TO_DATA_DIR: '/home/milkyway/Desktop/Student Thesis/Datasets/RGB_frames/'
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision

RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0

SOLVER:
  BASE_LR: 0.01  # Lower LR for distillation
  LR_POLICY: cosine
  MAX_EPOCH: 180 # default is 120
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
  EARLY_STOPPING:
    ENABLE: False
    PATIENCE: 3 # since we do evaluation every 5 epochs, this means we will wait for 15 epochs before stopping
    MIN_DELTA: 0.001
    METRIC: "top1_err"  # or "top5_err"
    MODE: "min"  # "min" for error metrics, "max" for accuracy metrics

MODEL:
  NUM_CLASSES: 61 # Number of classes in the dataset
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  HEAD_ACT: "same"

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: False

NUM_GPUS: 1  # Adjust based on available resources
RNG_SEED: 42
OUTPUT_DIR: "/home/milkyway/Desktop/Student Thesis/Slowfast/slowfast/intermediate_results/distillation_output_exp9"

TENSORBOARD:
  ENABLE: True


PRUNING:
  ENABLE: True