PRUNING:
  ENABLE: True
  GLOBAL: True
  ISOMORPHIC: True
  PRUNING_METHOD: 'l1'
  PRUNING_RATE: 0.25
  PRUNING_MAX_RATE: 0.25
  CHECKPOINT_FILE_PATH: '/home/milkyway/Desktop/Student Thesis/results/x3d_M_exp1/checkpoints/checkpoint_epoch_00120.pyth'
  CHECKPOINT_TYPE: pytorch
  EVALUATE_AFTER_FINE_TUNNING: True

TRAIN:
  # ENABLE: False # default True
  ENABLE: False
  DATASET: meccano
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 20
  AUTO_RESUME: True
  CHECKPOINT_TYPE: pytorch

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

TEST:
  ENABLE: True
  DATASET: meccano
  BATCH_SIZE: 128
  CHECKPOINT_FILE_PATH: '' # 76.21% top1 30-view accuracy to download from the model zoo (optional).
  # NUM_SPATIAL_CROPS: 1
  NUM_SPATIAL_CROPS: 3

DATA:
  PATH_TO_DATA_DIR: '/home/milkyway/Desktop/Student Thesis/Datasets/RGB_frames/'
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  # TEST_CROP_SIZE: 224 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 256 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision

RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0

SOLVER:
  BASE_LR: 0.1 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 120
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
  EARLY_STOPPING:
    ENABLE: True
    PATIENCE: 10
    MIN_DELTA: 0.001
    METRIC: "top1_err"  # or "top5_err"
    MODE: "min"  # "min" for error metrics, "max" for accuracy metrics
    RESTORE_BEST_WEIGHTS: True

MODEL:
  NUM_CLASSES: 61
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: False

NUM_GPUS: 1
RNG_SEED: 0
OUTPUT_DIR: '/home/milkyway/Desktop/Student Thesis/Slowfast/slowfast/intermediate_results/X3D_M_pruned_exp5'
